import { User } from "@/app/types/user";
import { EventData, EventStatus } from "@/app/types/event";
import { NFTTicket, TicketType } from "@/app/types/ticket";
import { Campaign, Investment } from "@/app/types/campaign";

// Dummy Users
export const dummyUsers: User[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@organizer.com",
    role: "organizer",
    walletAddress: "8xK...9pL2",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "2",
    name: "Mike Chen",
    email: "mike@staff.com",
    role: "staff",
    walletAddress: "4yH...3mN9",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Mike",
    createdAt: new Date("2024-03-20"),
  },
  {
    id: "3",
    name: "Emily Davis",
    email: "emily@customer.com",
    role: "customer",
    walletAddress: "2qW...7kP4",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emily",
    createdAt: new Date("2024-05-10"),
  },
  {
    id: "4",
    name: "Admin Mythra",
    email: "admin@mythra.io",
    role: "admin",
    walletAddress: "9zX...1cV8",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Admin",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "5",
    name: "Alex Rivera",
    email: "alex@investor.com",
    role: "investor",
    walletAddress: "5tR...6bM3",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alex",
    createdAt: new Date("2024-02-14"),
  },
];

// Dummy Events
export const dummyEvents: EventData[] = [
  {
    id: "evt-1",
    name: "Web3 Summit 2025",
    description:
      "The biggest Web3 conference of the year featuring top speakers from blockchain industry.",
    organizerId: "1",
    organizerName: "Sarah Johnson",
    category: "Conference",
    coverImage:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    location: "Singapore Expo",
    venue: "Hall 5A",
    date: new Date("2025-11-15"),
    start_time: new Date("2025-11-15T09:00:00"),
    end_time: new Date("2025-11-15T18:00:00"),
    startTime: "09:00",
    endTime: "18:00",
    totalTickets: 1000,
    soldTickets: 750,
    maxTickets: 1000,
    ticketsSold: 750,
    priceInSOL: 0.5,
    revenue: 37500,
    status: EventStatus.PUBLISHED,
    creatorWallet: "8xK...9pL2",
    ticketTypes: [
      {
        id: "tt-1",
        name: "Early Bird",
        description: "Limited early bird tickets",
        price: 50,
        totalSupply: 200,
        sold: 200,
        available: 0,
        benefits: [
          "Access to all sessions",
          "Welcome kit",
          "Networking dinner",
        ],
      },
      {
        id: "tt-2",
        name: "General Admission",
        description: "Standard conference pass",
        price: 75,
        totalSupply: 600,
        sold: 450,
        available: 150,
        benefits: ["Access to all sessions", "Welcome kit"],
      },
      {
        id: "tt-3",
        name: "VIP Pass",
        description: "Premium experience with exclusive perks",
        price: 150,
        totalSupply: 200,
        sold: 100,
        available: 100,
        benefits: [
          "Access to all sessions",
          "VIP lounge",
          "Meet & greet",
          "Premium swag",
        ],
      },
    ],
    staffIds: ["2"],
    createdAt: new Date("2024-08-01"),
    updatedAt: new Date("2024-08-01"),
    poolBalance: 26250, // 70% of revenue
  },
  {
    id: "evt-2",
    name: "NFT Art Gala",
    description: "Exclusive NFT art exhibition and auction event.",
    organizerId: "1",
    organizerName: "Sarah Johnson",
    category: "Art",
    coverImage:
      "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800",
    location: "Art Gallery NYC",
    venue: "Main Hall",
    date: new Date("2025-12-01"),
    start_time: new Date("2025-12-01T19:00:00"),
    end_time: new Date("2025-12-01T23:00:00"),
    startTime: "19:00",
    endTime: "23:00",
    totalTickets: 300,
    soldTickets: 180,
    maxTickets: 300,
    ticketsSold: 180,
    priceInSOL: 0.8,
    revenue: 18000,
    status: EventStatus.PUBLISHED,
    creatorWallet: "8xK...9pL2",
    ticketTypes: [
      {
        id: "tt-4",
        name: "Gallery Access",
        description: "View the exhibition",
        price: 80,
        totalSupply: 200,
        sold: 120,
        available: 80,
        benefits: ["Gallery access", "Welcome drink"],
      },
      {
        id: "tt-5",
        name: "Collector Pass",
        description: "Bidding privileges",
        price: 150,
        totalSupply: 100,
        sold: 60,
        available: 40,
        benefits: [
          "Gallery access",
          "Auction participation",
          "Catalog",
          "Dinner",
        ],
      },
    ],
    staffIds: ["2"],
    createdAt: new Date("2024-09-15"),
    updatedAt: new Date("2024-09-15"),
    poolBalance: 12600,
  },
  {
    id: "evt-3",
    name: "DeFi Workshop",
    description: "Learn about decentralized finance from industry experts.",
    organizerId: "1",
    organizerName: "Sarah Johnson",
    category: "Workshop",
    coverImage:
      "https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800",
    location: "Online",
    venue: "Zoom Webinar",
    date: new Date("2025-10-20"),
    start_time: new Date("2025-10-20T14:00:00"),
    end_time: new Date("2025-10-20T17:00:00"),
    startTime: "14:00",
    endTime: "17:00",
    totalTickets: 500,
    soldTickets: 320,
    maxTickets: 500,
    ticketsSold: 320,
    priceInSOL: 0.3,
    revenue: 9600,
    status: EventStatus.DRAFT,
    creatorWallet: "8xK...9pL2",
    ticketTypes: [
      {
        id: "tt-6",
        name: "Workshop Access",
        description: "Live workshop participation",
        price: 30,
        totalSupply: 500,
        sold: 320,
        available: 180,
        benefits: ["Live session", "Q&A access", "Recording"],
      },
    ],
    staffIds: [],
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2024-09-01"),
    poolBalance: 0,
  },
];

// Dummy NFT Tickets
export const dummyTickets: NFTTicket[] = [
  {
    id: "nft-1",
    eventId: "evt-1",
    eventName: "Web3 Summit 2025",
    ticketType: "VIP Pass",
    price: 150,
    owner: "3",
    status: "active",
    nftMetadata: {
      image:
        "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400",
      name: "Web3 Summit 2025 - VIP Pass #001",
      description: "VIP access to Web3 Summit 2025",
      attributes: [
        { trait_type: "Type", value: "VIP Pass" },
        { trait_type: "Event", value: "Web3 Summit 2025" },
        { trait_type: "Date", value: "2025-11-15" },
      ],
    },
    purchasedAt: new Date("2024-08-15"),
  },
  {
    id: "nft-2",
    eventId: "evt-2",
    eventName: "NFT Art Gala",
    ticketType: "Collector Pass",
    price: 150,
    owner: "3",
    status: "active",
    nftMetadata: {
      image: "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=400",
      name: "NFT Art Gala - Collector Pass #045",
      description: "Collector access with bidding privileges",
      attributes: [
        { trait_type: "Type", value: "Collector Pass" },
        { trait_type: "Event", value: "NFT Art Gala" },
        { trait_type: "Date", value: "2025-12-01" },
      ],
    },
    purchasedAt: new Date("2024-09-20"),
  },
];

// Dummy Campaigns
export const dummyCampaigns: Campaign[] = [
  {
    id: "camp-1",
    eventId: "evt-1",
    eventName: "Web3 Summit 2025",
    organizerId: "1",
    organizerName: "Sarah Johnson",
    title: "Help us bring Web3 Summit to Singapore!",
    description:
      "Support the biggest Web3 conference and get exclusive rewards.",
    coverImage:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800",
    targetAmount: 50000,
    currentAmount: 38500,
    minInvestment: 100,
    investors: 42,
    status: "active",
    startDate: new Date("2024-08-01"),
    endDate: new Date("2025-10-01"),
    rewards: [
      {
        id: "rwd-1",
        title: "Supporter",
        description: "Thank you for your support!",
        minAmount: 100,
        benefits: ["DAO tokens", "Exclusive NFT badge"],
        claimed: 15,
        total: 50,
      },
      {
        id: "rwd-2",
        title: "Patron",
        description: "Generous support",
        minAmount: 500,
        benefits: ["DAO tokens", "Free VIP ticket", "Backstage access"],
        claimed: 20,
        total: 30,
      },
      {
        id: "rwd-3",
        title: "Champion",
        description: "Premium supporter",
        minAmount: 1000,
        benefits: [
          "DAO tokens",
          "2 VIP tickets",
          "Speaker dinner",
          "Logo placement",
        ],
        claimed: 7,
        total: 10,
      },
    ],
    votes: 156,
    votingThreshold: 100,
  },
  {
    id: "camp-2",
    eventId: "evt-2",
    eventName: "NFT Art Gala",
    organizerId: "1",
    organizerName: "Sarah Johnson",
    title: "Fund the NFT Art Gala Exhibition",
    description: "Be part of the most exclusive NFT art event.",
    coverImage:
      "https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800",
    targetAmount: 30000,
    currentAmount: 22500,
    minInvestment: 250,
    investors: 28,
    status: "active",
    startDate: new Date("2024-09-01"),
    endDate: new Date("2025-11-01"),
    rewards: [
      {
        id: "rwd-4",
        title: "Art Supporter",
        description: "Support the arts",
        minAmount: 250,
        benefits: ["DAO tokens", "Gallery pass", "Art catalog"],
        claimed: 18,
        total: 40,
      },
      {
        id: "rwd-5",
        title: "Art Patron",
        description: "Major supporter",
        minAmount: 1000,
        benefits: [
          "DAO tokens",
          "Collector pass",
          "Private tour",
          "Artist meet",
        ],
        claimed: 10,
        total: 15,
      },
    ],
    votes: 89,
    votingThreshold: 50,
  },
];

// Dummy Investments
export const dummyInvestments: Investment[] = [
  {
    id: "inv-1",
    campaignId: "camp-1",
    investorId: "5",
    amount: 500,
    rewardId: "rwd-2",
    daoTokens: 5000,
    investedAt: new Date("2024-08-10"),
    status: "active",
  },
  {
    id: "inv-2",
    campaignId: "camp-2",
    investorId: "5",
    amount: 1000,
    rewardId: "rwd-5",
    daoTokens: 10000,
    investedAt: new Date("2024-09-05"),
    status: "active",
  },
];
